### PR TITLE
Fix picker width patch for Madrid

### PR DESCRIPTION
**Pull request by johncaruso**
Might be a better way to do this, but figure I'd submit for anyone using Madrid.

### CODE REVIEW

**Comment by jneale** [comment]
Thanks for this John. I'll need to check it's backwards compatible but this is really helpful. Cheers

**Comment by tdeniston** [comment]
For some reason, this isn't working for me. I have logged out, reloaded, etc. This is an instance that started at London and migrated to Madrid. UI Script was installed prior to upgrade and I manually made the change on the specified lines. 

Madrid Patch 0 HF 1

**Comment by johncaruso** [comment]
Yeah, I did this on a clean Madrid PDI, so not sure how the upgrade from London might differ. Don't have access to an upgraded from London instance. Maybe James does?

**Comment by johncaruso** [comment]
@tdeniston I just tried this patch on a PDI upgraded from London to Madrid. It worked for me. You may have some local customization affecting things (custom CSS, e.g.,). 

The banner HTML structure is pretty much the same between London and Madrid. It was a CSS change on the .nav-header class adding `display: flex` that broke the picker width calculation.

Another approach to fixing this could be to patch the CSS so that .navbar-header does not have that `display: flex` added.

However, removing that may break mobile views or something else that might depend on it.

**Comment by tdeniston** [comment]
It looks like at some point the Global checkbox became unchecked, which appears to have caused the issue. Once it was checked again, it worked fine.

**Comment by jneale** [comment]
Hi guys, thanks for highlighting this and contributing! I've ended up fixing this slightly differently to account for any other header changes and it's now available on Share - compatible with J-M releases.

**Pull request closed without merging**
